--
-- PostgreSQL database dump
--


-- Dumped from database version 16.12
-- Dumped by pg_dump version 16.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    address character varying(255),
    email character varying(180) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(30)
);


--
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidature_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candidature_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    author character varying(255) NOT NULL,
    content text NOT NULL,
    flag_label character varying(255),
    flag_reason text,
    flag_score double precision,
    is_flagged boolean NOT NULL,
    resume_url character varying(255),
    candidature_id bigint NOT NULL,
    CONSTRAINT candidature_messages_author_check CHECK (((author)::text = ANY ((ARRAY['FREELANCER'::character varying, 'CLIENT'::character varying])::text[])))
);


--
-- Name: candidature_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.candidature_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidature_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidatures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candidatures (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    client_message text,
    cover_letter text,
    proposed_duration integer,
    proposed_price double precision,
    resume_url character varying(255),
    status character varying(255) NOT NULL,
    freelancer_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    CONSTRAINT candidatures_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: candidatures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.candidatures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidatures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    address text,
    bio text,
    city character varying(255),
    company_name character varying(255),
    company_size character varying(255),
    country character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    industry character varying(255),
    is_verified boolean NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    postal_code character varying(255),
    profile_picture character varying(255),
    verification_token character varying(255),
    website character varying(255)
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competences (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    certification_date date,
    certification_name character varying(255),
    description character varying(255),
    is_certified boolean NOT NULL,
    level character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    years_of_experience integer,
    freelancer_id bigint NOT NULL
);


--
-- Name: competences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contrats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contrats (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    description text,
    end_date date,
    etat character varying(255) NOT NULL,
    milestone_based boolean NOT NULL,
    payment_terms character varying(255),
    start_date date,
    terms text,
    title character varying(255) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    client_id bigint NOT NULL,
    freelancer_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    CONSTRAINT contrats_etat_check CHECK (((etat)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: contrats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contrats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domaines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domaines (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    color character varying(255),
    description text,
    icon character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: domaines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domaines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domaines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedbacks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    author_user_id bigint NOT NULL,
    comment character varying(2000),
    direction character varying(40) NOT NULL,
    rating integer NOT NULL,
    target_user_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    CONSTRAINT feedbacks_direction_check CHECK (((direction)::text = ANY ((ARRAY['CLIENT_TO_FREELANCER'::character varying, 'FREELANCER_TO_CLIENT'::character varying])::text[])))
);


--
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: freelancers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.freelancers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    address text,
    availability character varying(255),
    bio text,
    city character varying(255),
    country character varying(255),
    daily_rate numeric(10,2),
    date_of_birth date,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    gender character varying(255),
    github_url character varying(255),
    hourly_rate numeric(10,2),
    is_available boolean NOT NULL,
    is_verified boolean NOT NULL,
    last_name character varying(255) NOT NULL,
    linkedin_url character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    portfolio_url character varying(255),
    postal_code character varying(255),
    profile_picture character varying(255),
    rating numeric(3,2),
    skills text,
    success_rate numeric(5,2),
    title character varying(255),
    total_projects integer,
    verification_token character varying(255)
);


--
-- Name: freelancers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.freelancers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.freelancers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    content text NOT NULL,
    flag_label character varying(255),
    flag_reason text,
    flag_score double precision,
    is_flagged boolean NOT NULL,
    is_read boolean NOT NULL,
    message_type character varying(255),
    subject character varying(255),
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: milestone_deliverables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.milestone_deliverables (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    comment text,
    content_type character varying(255),
    file_name character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL,
    milestone_id bigint NOT NULL,
    uploader_id bigint NOT NULL
);


--
-- Name: milestone_deliverables_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.milestone_deliverables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.milestone_deliverables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: milestones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.milestones (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    amount numeric(10,2) NOT NULL,
    completion_date date,
    completion_notes text,
    deliverable_comment text,
    deliverable_file_name character varying(255),
    deliverable_file_size bigint,
    deliverable_file_type character varying(255),
    deliverable_original_name character varying(255),
    deliverable_uploaded_at timestamp(6) without time zone,
    description text,
    due_date date,
    is_completed boolean NOT NULL,
    order_index integer NOT NULL,
    paid_at timestamp(6) without time zone,
    rejection_reason text,
    status character varying(32) NOT NULL,
    title character varying(255) NOT NULL,
    mission_id bigint NOT NULL,
    CONSTRAINT milestones_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'IN_PROGRESS'::character varying, 'SUBMITTED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying, 'PAID'::character varying])::text[])))
);


--
-- Name: milestones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: missions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.missions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    attachments text,
    budget_max numeric(10,2),
    budget_min numeric(10,2),
    budget_type character varying(255) NOT NULL,
    deadline date,
    description text NOT NULL,
    estimated_duration integer,
    is_urgent boolean NOT NULL,
    niveau_experience character varying(255) NOT NULL,
    requirements text,
    skills_required text,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type_travail character varying(255) NOT NULL,
    assigned_freelancer_id bigint,
    client_id bigint NOT NULL,
    domaine_id bigint NOT NULL,
    CONSTRAINT missions_budget_type_check CHECK (((budget_type)::text = ANY ((ARRAY['FIXED'::character varying, 'HOURLY'::character varying, 'NEGOTIABLE'::character varying])::text[]))),
    CONSTRAINT missions_niveau_experience_check CHECK (((niveau_experience)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[]))),
    CONSTRAINT missions_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'IN_PROGRESS'::character varying, 'PENDING_CLOSURE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'PAUSED'::character varying])::text[]))),
    CONSTRAINT missions_type_travail_check CHECK (((type_travail)::text = ANY ((ARRAY['REMOTE'::character varying, 'ON_SITE'::character varying, 'HYBRID'::character varying])::text[])))
);


--
-- Name: missions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.missions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.missions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    amount numeric(10,2) NOT NULL,
    description character varying(255),
    failure_reason character varying(255),
    gateway_transaction_id character varying(255),
    payment_gateway character varying(255),
    payment_method character varying(255),
    processed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    transaction_reference character varying(255) NOT NULL,
    client_id bigint NOT NULL,
    freelancer_id bigint NOT NULL,
    milestone_id bigint,
    mission_id bigint NOT NULL,
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    amount numeric(10,2) NOT NULL,
    description character varying(255),
    type character varying(255) NOT NULL,
    milestone_id bigint,
    mission_id bigint,
    wallet_id bigint NOT NULL,
    CONSTRAINT wallet_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying, 'RECHARGE'::character varying])::text[])))
);


--
-- Name: wallet_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    balance numeric(10,2) NOT NULL,
    currency character varying(255) NOT NULL,
    client_id bigint,
    freelancer_id bigint
);


--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: candidature_messages candidature_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidature_messages
    ADD CONSTRAINT candidature_messages_pkey PRIMARY KEY (id);


--
-- Name: candidatures candidatures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidatures
    ADD CONSTRAINT candidatures_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: competences competences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competences
    ADD CONSTRAINT competences_pkey PRIMARY KEY (id);


--
-- Name: contrats contrats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT contrats_pkey PRIMARY KEY (id);


--
-- Name: domaines domaines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domaines
    ADD CONSTRAINT domaines_pkey PRIMARY KEY (id);


--
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- Name: freelancers freelancers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.freelancers
    ADD CONSTRAINT freelancers_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: milestone_deliverables milestone_deliverables_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_deliverables
    ADD CONSTRAINT milestone_deliverables_pkey PRIMARY KEY (id);


--
-- Name: milestones milestones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestones
    ADD CONSTRAINT milestones_pkey PRIMARY KEY (id);


--
-- Name: missions missions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT missions_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: wallets uk66y023qyrgjddwefwbisbfmgf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uk66y023qyrgjddwefwbisbfmgf UNIQUE (freelancer_id);


--
-- Name: transactions uk94m9euoxupnom1p8mtwmk9q4g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk94m9euoxupnom1p8mtwmk9q4g UNIQUE (transaction_reference);


--
-- Name: admins uk_admin_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT uk_admin_email UNIQUE (email);


--
-- Name: feedbacks uk_feedback_mission_author; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT uk_feedback_mission_author UNIQUE (mission_id, author_user_id);


--
-- Name: freelancers ukcshyo4ppk1864qqe0j2t112ss; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.freelancers
    ADD CONSTRAINT ukcshyo4ppk1864qqe0j2t112ss UNIQUE (email);


--
-- Name: wallets ukh1msak25um4x4pxmxytm0vho0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT ukh1msak25um4x4pxmxytm0vho0 UNIQUE (client_id);


--
-- Name: contrats ukoatebb687tc0d3qfskvrhblxt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT ukoatebb687tc0d3qfskvrhblxt UNIQUE (mission_id);


--
-- Name: domaines ukpxsy2atfs95vfj4squb524tpc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domaines
    ADD CONSTRAINT ukpxsy2atfs95vfj4squb524tpc UNIQUE (name);


--
-- Name: milestone_deliverables ukrxxffocu9trhkrwsdyvnpvqsl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_deliverables
    ADD CONSTRAINT ukrxxffocu9trhkrwsdyvnpvqsl UNIQUE (storage_key);


--
-- Name: clients uksrv16ica2c1csub334bxjjb59; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);


--
-- Name: wallet_transactions wallet_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: idx_feedback_mission; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_mission ON public.feedbacks USING btree (mission_id);


--
-- Name: idx_feedback_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_target ON public.feedbacks USING btree (target_user_id);


--
-- Name: transactions fk1cv1nehchsmmql29xvl4ibqnq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk1cv1nehchsmmql29xvl4ibqnq FOREIGN KEY (freelancer_id) REFERENCES public.freelancers(id);


--
-- Name: missions fk3tm5u2w3totrqyjvujyiosvvt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT fk3tm5u2w3totrqyjvujyiosvvt FOREIGN KEY (domaine_id) REFERENCES public.domaines(id);


--
-- Name: milestone_deliverables fk4cj4dh9iwjccm9g3bt7xto88f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_deliverables
    ADD CONSTRAINT fk4cj4dh9iwjccm9g3bt7xto88f FOREIGN KEY (milestone_id) REFERENCES public.milestones(id);


--
-- Name: candidature_messages fk4djo67svm3dwm2jllq244bi01; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidature_messages
    ADD CONSTRAINT fk4djo67svm3dwm2jllq244bi01 FOREIGN KEY (candidature_id) REFERENCES public.candidatures(id);


--
-- Name: milestone_deliverables fk62pc2fsx48v6oiq4tbs3lv60p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_deliverables
    ADD CONSTRAINT fk62pc2fsx48v6oiq4tbs3lv60p FOREIGN KEY (uploader_id) REFERENCES public.freelancers(id);


--
-- Name: missions fk6k9rd1koyhf390lclpamg4xjf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT fk6k9rd1koyhf390lclpamg4xjf FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: contrats fk6srdnq8er5whck61gniso2b4q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT fk6srdnq8er5whck61gniso2b4q FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: candidatures fk6xihumsqeh5lxabaxv9w5sb2q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidatures
    ADD CONSTRAINT fk6xihumsqeh5lxabaxv9w5sb2q FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: missions fk75ve1rem2uhx9osexten3udv3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT fk75ve1rem2uhx9osexten3udv3 FOREIGN KEY (assigned_freelancer_id) REFERENCES public.freelancers(id);


--
-- Name: wallet_transactions fk8seu7b87ifqi09ghhssusmb0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fk8seu7b87ifqi09ghhssusmb0x FOREIGN KEY (wallet_id) REFERENCES public.wallets(id);


--
-- Name: transactions fk8upk4fbv02nfxeo39353mt5rr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk8upk4fbv02nfxeo39353mt5rr FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: contrats fk8xusiifssotl2lgep3a6p3x54; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT fk8xusiifssotl2lgep3a6p3x54 FOREIGN KEY (freelancer_id) REFERENCES public.freelancers(id);


--
-- Name: wallet_transactions fk9qopyigyfklsbuhgnbsvi3clm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fk9qopyigyfklsbuhgnbsvi3clm FOREIGN KEY (milestone_id) REFERENCES public.milestones(id);


--
-- Name: feedbacks fkfatesfib5tf3m8ddnndx1vhu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fkfatesfib5tf3m8ddnndx1vhu FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: milestones fkhirc5rlu6vflbrsvv9dn9vg0l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestones
    ADD CONSTRAINT fkhirc5rlu6vflbrsvv9dn9vg0l FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: messages fkhldlthynlnp1d04ftgn4xvddp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkhldlthynlnp1d04ftgn4xvddp FOREIGN KEY (sender_id) REFERENCES public.clients(id);


--
-- Name: contrats fkjar58d0r4op21itimeki1fty5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT fkjar58d0r4op21itimeki1fty5 FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: transactions fkjp6w7dmqrj0h9vykk2pbtik2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkjp6w7dmqrj0h9vykk2pbtik2 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: transactions fkk06t2hb533pfiufdc622cpekw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkk06t2hb533pfiufdc622cpekw FOREIGN KEY (milestone_id) REFERENCES public.milestones(id);


--
-- Name: wallet_transactions fkljw9tp5rqvtobexfjrxwrfog0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fkljw9tp5rqvtobexfjrxwrfog0 FOREIGN KEY (mission_id) REFERENCES public.missions(id);


--
-- Name: competences fkndqh5wirvkrqkb4c4ucqkd63c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competences
    ADD CONSTRAINT fkndqh5wirvkrqkb4c4ucqkd63c FOREIGN KEY (freelancer_id) REFERENCES public.freelancers(id);


--
-- Name: wallets fkp9ymnoc3c7cynx0lmo7qmkw7t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkp9ymnoc3c7cynx0lmo7qmkw7t FOREIGN KEY (freelancer_id) REFERENCES public.freelancers(id);


--
-- Name: messages fkr6k20uj61bx98pqfmkr00og4v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkr6k20uj61bx98pqfmkr00og4v FOREIGN KEY (receiver_id) REFERENCES public.freelancers(id);


--
-- Name: wallets fkrog16b0y1jucy75kpvij66b80; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkrog16b0y1jucy75kpvij66b80 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: candidatures fkrw347mv3wkntu2amis1cyx3d6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidatures
    ADD CONSTRAINT fkrw347mv3wkntu2amis1cyx3d6 FOREIGN KEY (freelancer_id) REFERENCES public.freelancers(id);


--
-- PostgreSQL database dump complete
--


